name: code-server
services:
  coturn:
    image: codercom/code-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - "$HOME/.local:/home/coder/.local"
      - "$HOME/.config:/home/coder/.config"
      - "$PWD:/home/coder/project"
    environment:
      - DOCKER_USER=$USER
    user: "$(id -u):$(id -g)"
