name: build-php-cli-windows-2025

on:
  push:
  pull_request:

env:
  BUILD_PHP_VERSION: 8.2.13

jobs:
  windows-native:
    if: 0
    runs-on: windows-2025
    # runs-on: windows-11-arm
    strategy:
      matrix:
        php-version:
          #  - "8.2.13"
          #  - "8.1.27"
          - "8.3.7"

    steps:
      - uses: actions/checkout@v4
      - name: show environment info
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all
          echo "BUILD_PHP_VERSION=${{ matrix.php-version }}" >> $Env:GITHUB_ENV

      #      - uses: msys2/setup-msys2@v2
      #        with:
      #          install: >-
      #            curl git
      - name: prepare
        shell: cmd
        run: |
          echo %ProgramFiles(x86)%
          echo %USERPROFILE%
          echo %NUMBER_OF_PROCESSORS%
          git clone -b master https://github.com/php/php-sdk-binary-tools.git
          set "__PROJECT__=%cd%"
          set "PATH=%PATH%;%__PROJECT__%\php-sdk-binary-tools\bin\;%__PROJECT__%\php-sdk-binary-tools\msys2\usr\bin\;"
          vswhere.exe
          vswhere.exe -legacy -prerelease -format json


      - name: set swap
        if: 0
        shell: cmd
        run: |
          wmic diskdrive list brief
          wmic logicaldisk
          :: 查看分页设置
          wmic pagefile list /format:list
          :: wmic computersystem where name="%computername%" set AutomaticManagedPagefile=True
          :: 禁用自动管理 分页大小
          wmic computersystem where name="%computername%" set AutomaticManagedPagefile=False
          :: 设置分页大小
          wmic pagefileset where name="D:\\pagefile.sys" set InitialSize=2048,MaximumSize=4096
          wmic pagefile list /format:list
